default: &db_sqlite3
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

default: &db_postgresql
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: postgres
  # password: root
  # host: 127.0.0.1
  # port: 5432

default: &db__mysql
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 127.0.0.1

development:
  <<: *db_postgresql
  database: selectize_development
  # database: db/development.sqlite3

test:
  <<: *db_postgresql
  database: selectize_test
  # database: db/test.sqlite3

production:
  <<: *db_postgresql
  database: selectize_development
  # database: db/production.sqlite3




